### ISSUE TITLE
Remove compatibility-kit to its own repo

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#2005]
### 🤔 What's the problem you've observed?

[Break up the monorepo](https://github.com/orgs/cucumber/projects/12/views/3)

### TODO

- [x] Copy commits over to https://github.com/cucumber/compatibility-kit/
- [x] Replace path dependencies on compatibility kit with dependency on published package instead
- [x] Remove the `compatibilty-kit` folder
- [x] Move any tickets over to https://github.com/cucumber/compatibility-kit/
----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by aurelien-reeves** [comment]
For the polyglot repo to be ready, we need to:

- [ ] Move features and ndjson into a `samples` folder (in progress: refs. https://github.com/cucumber/compatibility-kit/pull/4)
- [ ] Make JS tests pass
- [ ] Make ruby tests pass
- [ ] Create github workflows
- [ ] Cleanup the repo from mono-repo related stuff
- [ ] Make a release workflow
